server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medical_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: kotlin-spring-api

logging:
  level:
    com.medical.management: DEBUG
    org.springframework.web: INFO
