server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/medical_data
    username: admin
    password: medical_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: kotlin-spring-api
